include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**.config.dart'
    - '**.g.dart'
  errors:
    todo: ignore
    invalid_annotation_target: ignore

linter:
  rules:
    unawaited_futures: true
    avoid_relative_lib_imports: true
    cancel_subscriptions: true
    close_sinks: true
    unnecessary_brace_in_string_interps: false
    prefer_single_quotes: true
    depend_on_referenced_packages: false