name: shuffle_uikit
description: This project is a collection of UI kit in Shuffle app of Azart Technologies
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.1 <=4.0.0'
  flutter: ">=3.7.2"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
   sdk: flutter

  #ui utils
  flutter_svg: ^2.0.7
  flutter_cache_manager: ^3.3.1
  flutter_screenutil: ^5.7.0

  #ui widgets
  cached_network_image: ^3.2.3
  gradient_borders: ^1.0.0
  shimmer: ^3.0.0
  flutter_html: ^3.0.0-beta.2
  auto_size_text: ^3.0.0
  url_launcher: ^6.1.11
  flutter_html_iframe: any
  flutter_html_svg: any
  pinput:
    git:
      url: https://github.com/donik1998/Flutter_Pinput.git
      ref: master
  sliver_tools: ^0.2.10
  infinite_scroll_pagination: ^4.0.0-dev.1
  wheel_slider: ^1.1.1
  carousel_slider: ^4.2.1
  card_swiper: ^3.0.1
  flutter_gallery_3d: ^1.1.1

  #dialogs widgets
  popover: ^0.2.8+2

  #tab navigation
  tabnavigator: ^1.0.0
  rxdart: any
  lottie: ^2.3.2
  flutter_card_swiper: ^5.0.0
  intl: ^0.18.1
  just_audio: ^0.9.33

  #custom splash factory
  flutter_platform_widgets: ^4.0.0-beta.1
  dynamic_color: ^1.6.5
  video_player: ^2.7.0
  smooth_video_progress: ^0.0.4
  countries_flag: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.3.1
  build_runner: ^2.3.3
  dart_code_metrics: ^5.7.3

flutter:
  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/fonts/
    - assets/audio/
    - assets/animations/lottie/

  fonts:
    - family: Unbounded
      fonts:
        - asset: assets/fonts/Unbounded-Light.ttf
          weight: 300
        - asset: assets/fonts/Unbounded-Regular.ttf
          weight: 400
        - asset: assets/fonts/Unbounded-Medium.ttf
          weight: 500
        - asset: assets/fonts/Unbounded-SemiBold.ttf
          weight: 600

flutter_gen:
  output: lib/tokens
  line_length: 120
  integrations:
    flutter_svg: true
    lottie: true
  assets:
    enabled: true
    fonts:
      enabled: false
    output:
      style: dot-delimiter
      package_parameter_enabled: true
      synthetic-package: false