name: shuffle_uikit
description: This project is a collection of UI kit in Shuffle app of Azart Technologies
version: 0.0.1
homepage: none
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.4"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  #ui utils
  flutter_svg: ^2.0.8
  flutter_cache_manager: ^3.3.1
  flutter_screenutil: ^5.9.0
  vibration: ^1.8.2

  #ui widgets
  cached_network_image: ^3.3.0
  gradient_borders: ^1.0.0
  shimmer: ^3.0.0
  flutter_html: ^3.0.0-beta.2
  auto_size_text: ^3.0.0
  url_launcher: ^6.2.1
  flutter_html_iframe: any
  flutter_html_svg: any
  pointer_interceptor: ^0.9.3+6
  pinput:
    git:
      url: https://github.com/donik1998/Flutter_Pinput.git
      ref: master
  sliver_tools: ^0.2.12
  infinite_scroll_pagination: ^4.0.0-dev.1
  flutter_gallery_3d:
    #    path: ../flutter_gallery_3d_plus
    git:
      url: https://github.com/shuffle-app/flutter_gallery_3d_plus
      ref: 46c7407b35a841c81ad5972533f8d3d3b4fddd57
  flip_card: ^0.7.0

  #dialogs widgets
  popover: ^0.2.8+2

  #tab navigation
  tabnavigator:
    #    path: ../tabnavigator_plus
    git:
      url: https://github.com/shuffle-app/tabnavigator_plus
      ref: main
  rxdart: any
  lottie: ^2.7.0
  flutter_card_swiper:
    git:
      #      url: https://github.com/rel1nce/shuffle_swiper.git
      url: https://github.com/shuffle-app/shuffle_swiper.git
      #      ref: main
      ref: e4391ca40994c91acc563477c7959fbdeff50004

  intl: ^0.18.1
  just_audio: ^0.9.35

  #custom splash factory
  flutter_platform_widgets: ^4.0.0-beta.1
  dynamic_color: ^1.6.5
  video_player: ^2.8.2
  smooth_video_progress: ^0.0.4
  countries_flag: ^1.0.0

  #maps
  google_maps_flutter: ^2.5.0
  flutter_polyline_points: ^2.0.0

dependency_overrides:
  watcher: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.3.1
  build_runner: ^2.3.3
  icon_font_generator: ^4.0.0
#  dart_code_metrics: ^5.7.3
flutter:
  assets:
    - assets/images/png/
    - assets/images/png/preference_questions/
    - assets/images/svg/
    - assets/fonts/
    - assets/audio/
    - assets/animations/lottie/

  fonts:
    - family: Unbounded
      fonts:
        - asset: assets/fonts/Unbounded-Light.ttf
          weight: 300
        - asset: assets/fonts/Unbounded-Regular.ttf
          weight: 400
        - asset: assets/fonts/Unbounded-Medium.ttf
          weight: 500
        - asset: assets/fonts/Unbounded-SemiBold.ttf
          weight: 600
    - family: Shuffle Icons
      fonts:
        - asset: assets/fonts/shuffle_ui_kit_icons.otf

flutter_gen:
  output: lib/tokens
  line_length: 120
  integrations:
    flutter_svg: true
    lottie: true
  assets:
    enabled: true
    fonts:
      enabled: false
    output:
      style: dot-delimiter
      package_parameter_enabled: true
      synthetic-package: false

# extensions
flutter_intl:
  enabled: true
  arb_dir: lib/localization/arb
  output_dir: lib/localization

# icon_font_generator

# dart run icon_font_generator:generator assets/images/svg/ assets/fonts/shuffle_ui_kit_icons.otf

icon_font:
  input_svg_dir: "assets/images/svg/"
  output_font_file: "assets/fonts/shuffle_ui_kit_icons.otf"

  output_class_file: "lib/tokens/shuffle_ui_kit_icons.dart"
  class_name: "ShuffleUiKitIcons"
  package: shuffle_uikit
  format: true

  font_name: "Shuffle Icons"
  normalize: false
  ignore_shapes: false

  recursive: true
  verbose: false