name: shuffle_uikit
description: This project is a collection of UI kit in Shuffle app of Azart Technologies
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
   sdk: flutter
  flutter_svg: ^2.0.4
  flutter_cache_manager:
  cached_network_image:
  gradient_borders: ^1.0.0
  flutter_gen_runner: ^5.2.0
  build_runner: ^2.3.3
  flutter_screenutil: ^5.7.0

  #dialogs widgets
  popover: ^0.2.8+2
  simple_gradient_text: ^1.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  flutter_gen_core:
    git:
      url: https://github.com/jetpeter/flutter_gen
      path: packages/core
      ref: 785161759cf07319c59d5ecc9de4ef66662bcd95

flutter:
  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/fonts/

  fonts:
    - family: Syne
      fonts:
        - asset: assets/fonts/Syne-Regular.ttf
          weight: 400
        - asset: assets/fonts/Syne-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Syne-Bold.ttf
          weight: 700

flutter_gen:
  output: lib/tokens
  line_length: 120
  integrations:
    flutter_svg: true
  assets:
    enabled: true
    fonts:
      enabled: false
    output:
      style: dot-delimiter
      package_parameter_enabled: false
      synthetic-package: false