name: shuffle_uikit
description: This project is a collection of UI kit in Shuffle app of Azart Technologies
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
   sdk: flutter

  #ui utils
  flutter_svg: ^2.0.4
  flutter_cache_manager: ^3.3.0
  flutter_screenutil: ^5.7.0

  #ui widgets
  cached_network_image: ^3.2.3
  gradient_borders: ^1.0.0

  #dialogs widgets
  popover: ^0.2.8+2
  simple_gradient_text: ^1.2.4

  #tab navigation
  tabnavigator: ^1.0.0
  lottie: ^2.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.2.0
  build_runner: ^2.3.3

dependency_overrides:
  flutter_gen_core:
    git:
      url: https://github.com/jetpeter/flutter_gen
      path: packages/core
      ref: 785161759cf07319c59d5ecc9de4ef66662bcd95

flutter:
  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/fonts/
    - assets/animations/lottie/

  fonts:
    - family: Unbounded
      fonts:
        - asset: assets/fonts/Unbounded-Light.ttf
          weight: 300
        - asset: assets/fonts/Unbounded-Regular.ttf
          weight: 400
        - asset: assets/fonts/Unbounded-Medium.ttf
          weight: 500
        - asset: assets/fonts/Unbounded-SemiBold.ttf
          weight: 600

flutter_gen:
  output: lib/tokens
  line_length: 120
  integrations:
    flutter_svg: true
    lottie: true
  assets:
    enabled: true
    fonts:
      enabled: false
    output:
      style: dot-delimiter
      package_parameter_enabled: true
      synthetic-package: false